dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - Openzeppelin/openzeppelin-contracts-upgradeable@4.0.0
  - OpenZeppelin/openzeppelin-contracts@3.4.1
compiler:
  solc:
    remappings:
    - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
    - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.0.0"
    - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.1"

dotenv: .env
networks:
  development:
    verify: False
  ganache-local:
    verify: False
  polygon-test:
    verify: True
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}